# Assignment 3 Q4

In [17]:
import pandas as pd
import numpy as np
import re

In [7]:
df = pd.read_csv('Data/movies_awards.csv')
df.columns

Index(['totalSeasons', 'Plot', 'Rated', 'Response', 'Language', 'Title',
       'Country', 'Writer', 'Metascore', 'imdbRating', 'Director', 'Released',
       'Actors', 'Year', 'Genre', 'Awards', 'Runtime', 'Type', 'Poster',
       'imdbVotes', 'imdbID'],
      dtype='object')

In [11]:
df1 = df.dropna(subset=['Awards'])
df1.head()

,totalSeasons,Plot,Rated,Response,Language,Title,Country,Writer,Metascore,imdbRating,...,Released,Actors,Year,Genre,Awards,Runtime,Type,Poster,imdbVotes,imdbID
3,none,A historical classic drama in three acts; reto...,NaN,True,Portuguese,Who Are You?,Portugal,João Botelho; Almeida Garrett (play),NaN,6.1,...,23 Nov 2001,Patrícia Guerreiro; Suzana Borges; Rui Morisso...,2001,Drama; History,1 win & 2 nominations.,112 min,movie,http://ia.media-imdb.com/images/M/MV5BMTM1Mjdi...,189.0,tt0210930
4,none,A father (Williams) suspects his son (Jackson)...,R,True,English,Skeletons in the Closet,USA,Donna Powers; Wayne Powers,NaN,5.4,...,24 Jul 2001,Treat Williams; Linda Hamilton; Jonathan Jacks...,2001,Crime; Drama; Mystery,1 win.,100 min,movie,http://ia.media-imdb.com/images/M/MV5BMjA0NjA2...,603.0,tt0212513
5,none,Four perky; clueless cheerleaders from the Hap...,R,True,English,Cheerleader Ninjas,USA,Kevin Campbell,NaN,2.3,...,25 Nov 2003,Kira Reed Lorsch; Angela Brubaker; Jeff Nichol...,2002,Action; Comedy,1 nomination.,91 min,movie,http://ia.media-imdb.com/images/M/MV5BMjA3MTQ1...,881.0,tt0235280
6,none,Sandrine; a woman in her thirties gets tired o...,NaN,True,French,The Girl from Paris,France,Christian Carion; Eric Assous,64.0,6.8,...,05 Sep 2001,Michel Serrault; Mathilde Seigner; Jean-Paul R...,2001,Comedy; Drama,3 wins & 2 nominations.,103 min,movie,https://images-na.ssl-images-amazon.com/images...,1715.0,tt0240149
7,none,A rivalry develops between a showbiz veteran a...,R,True,English,The Final Curtain,UK; USA,John Hodge,NaN,5.8,...,12 Oct 2002,Peter O'Toole; Aidan Gillen; Adrian Lester; Ju...,2002,Drama,1 win & 1 nomination.,85 min,movie,http://ia.media-imdb.com/images/M/MV5BOGI4MmIw...,466.0,tt0243904

In [94]:
df2 = df1[['Title', 'Awards']]
df2.head()

                     Title                   Awards
3             Who Are You?   1 win & 2 nominations.
4  Skeletons in the Closet                   1 win.
5       Cheerleader Ninjas            1 nomination.
6      The Girl from Paris  3 wins & 2 nominations.
7        The Final Curtain    1 win & 1 nomination.

In [81]:
list1 = df2['Awards'].apply(lambda x:re.findall(r'Won \d+ ([]).',x)[0] if len(re.findall('Won \d+', x))!=0  else 0)
list1

In [95]:
df3 = df2.copy()
# df3['Win'] = df3['Awards'].apply(lambda x: re.findall('(\d+) win',x)[0] if(re.findall('\d+ win', x))  else 0)
df3['Golden Globe Nominated'] = df3['Awards'].apply(lambda x: int(re.findall('Nominated for (\d+) Golden Globe',x)[0]) if(re.findall('Nominated for \d+ Golden Globe', x))  else 0)
df3['Golden Globe Won'] = df3['Awards'].apply(lambda x: int(re.findall('Won (\d+) Golden Globe',x)[0]) if(re.findall('Won \d+ Golden Globe', x))  else 0)
df3['Primetime Emmys Nominated'] = df3['Awards'].apply(lambda x: int(re.findall('Nominated for (\d+) Primetime Emmys',x)[0]) if(re.findall('Nominated for \d+ Primetime Emmys', x))  else 0)
df3['Primetime Emmys Won'] = df3['Awards'].apply(lambda x: int(re.findall('Won (\d+) Primetime Emmys',x)[0]) if(re.findall('Won \d+ Primetime Emmys', x))  else 0)
df3['Oscars Nominated'] = df3['Awards'].apply(lambda x: int(re.findall('Nominated for (\d+) Oscars',x)[0]) if(re.findall('Nominated for \d+ Oscars', x))  else 0)
df3['Oscars Won'] = df3['Awards'].apply(lambda x: int(re.findall('Won (\d+) Oscars',x)[0]) if(re.findall('Won \d+ Oscars', x))  else 0)
df3['BAFTA Film Awards Nominated'] = df3['Awards'].apply(lambda x: int(re.findall('Nominated for (\d+) BAFTA Film Awards',x)[0]) if(re.findall('Nominated for \d+ BAFTA Film Awards', x))  else 0)
df3['BAFTA Film Awards Won'] = df3['Awards'].apply(lambda x: int(re.findall('Won (\d+) BAFTA Film Awards',x)[0]) if(re.findall('Won \d+ BAFTA Film Awards', x))  else 0)

In [97]:
df3.head()

,Title,Awards,Golden Globe Nominated,Golden Globe Won,Primetime Emmys Nominated,Primetime Emmys Won,Oscars Nominated,Oscars Won,BAFTA Film Awards Nominated,BAFTA Film Awards Won
3,Who Are You?,1 win & 2 nominations.,0,0,0,0,0,0,0,0
4,Skeletons in the Closet,1 win.,0,0,0,0,0,0,0,0
5,Cheerleader Ninjas,1 nomination.,0,0,0,0,0,0,0,0
6,The Girl from Paris,3 wins & 2 nominations.,0,0,0,0,0,0,0,0
7,The Final Curtain,1 win & 1 nomination.,0,0,0,0,0,0,0,0

In [112]:
# df3['Win'] = df3['Awards'].apply(lambda x: int(re.findall('(\d+) win',x)[0]) if(re.findall('\d+ win', x))  else 0)
df3['Win'] = df3['Awards'].apply(lambda x: int(re.findall('(\d+) win',x)[0]) if(re.findall('\d+ win', x))  else 0) +df3['Golden Globe Won'] + df3['Primetime Emmys Won'] + df3['Oscars Won'] + df3['BAFTA Film Awards Won']
df3['Nominations'] = df3['Awards'].apply(lambda x: int(re.findall('(\d+) nominations',x)[0]) if(re.findall('\d+ nominations', x))  else 0) + df3['Golden Globe Nominated'] + df3['Primetime Emmys Nominated'] + df3['Oscars Nominated'] + df3['BAFTA Film Awards Nominated']
df3

,Title,Awards,Golden Globe Nominated,Golden Globe Won,Primetime Emmys Nominated,Primetime Emmys Won,Oscars Nominated,Oscars Won,BAFTA Film Awards Nominated,BAFTA Film Awards Won,Nominations,Win
3,Who Are You?,1 win & 2 nominations.,0,0,0,0,0,0,0,0,2,1
4,Skeletons in the Closet,1 win.,0,0,0,0,0,0,0,0,0,1
5,Cheerleader Ninjas,1 nomination.,0,0,0,0,0,0,0,0,0,0
6,The Girl from Paris,3 wins & 2 nominations.,0,0,0,0,0,0,0,0,2,3
7,The Final Curtain,1 win & 1 nomination.,0,0,0,0,0,0,0,0,0,1
11,Crazy/Beautiful,5 nominations.,0,0,0,0,0,0,0,0,5,0
13,The Anniversary Party,2 wins & 5 nominations.,0,0,0,0,0,0,0,0,5,2
15,The Quiet American,Nominated for 1 Oscar. Another 13 wins & 13 no...,0,0,0,0,0,0,0,0,13,13
18,Like Cat and Mouse,5 wins & 4 nominations.,0,0,0,0,0,0,0,0,4,5
24,Punch-Drunk Love,Nominated for 1 Golden Globe. Another 14 wins ...,1,0,0,0,0,0,0,0,35,14
25,Romeo,3 wins & 2 nominations.,0,0,0,0,0,0,0,0,2,3
28,Academia de baile Gloria,1 nomination.,0,0,0,0,0,0,0,0,0,0
31,Return to Never Land,5 nominations.,0,0,0,0,0,0,0,0,5,0
34,Better Luck Tomorrow,1 win & 2 nominations.,0,0,0,0,0,0,0,0,2,1
37,A Grande Família,22 wins & 44 nominations.,0,0,0,0,0,0,0,0,44,22
38,El lado oscuro del corazón 2,1 win & 3 nominations.,0,0,0,0,0,0,0,0,3,1
39,Slap Shot 2: Breaking the Ice,1 win & 8 nominations.,0,0,0,0,0,0,0,0,8,1
43,Van Wilder: Party Liaison,2 nominations.,0,0,0,0,0,0,0,0,2,0
47,Black Box BRD,6 wins & 1 nomination.,0,0,0,0,0,0,0,0,0,6
50,24,Won 2 Golden Globes. Another 68 wins & 201 nom...,0,2,0,0,0,0,0,0,201,70
51,Alias,Won 1 Golden Globe. Another 31 wins & 143 nomi...,0,1,0,0,0,0,0,0,143,32
53,According to Jim,Nominated for 4 Primetime Emmys. Another 16 no...,0,0,4,0,0,0,0,0,20,0
54,The Education of Max Bickford,3 wins & 2 nominations.,0,0,0,0,0,0,0,0,2,3
56,A Padroeira,3 wins & 6 nominations.,0,0,0,0,0,0,0,0,6,3
62,Poker,2 wins.,0,0,0,0,0,0,0,0,0,2
69,No Regrets,6 wins & 4 nominations.,0,0,0,0,0,0,0,0,4,6
72,Swept Away,7 wins & 6 nominations.,0,0,0,0,0,0,0,0,6,7
76,McLeod's Daughters,9 wins & 30 nominations.,0,0,0,0,0,0,0,0,30,9
79,The Grim Adventures of Billy & Mandy,Won 1 Primetime Emmy. Another 1 win & 6 nomina...,0,0,0,0,0,0,0,0,6,1
84,The Big Time,1 nomination.,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
13668,Eat That Question: Frank Zappa in His Own Words,1 win.,0,0,0,0,0,0,0,0,0,1
13669,Norman Lear: Just Another Version of You,5 wins.,0,0,0,0,0,0,0,0,0,5
13699,The Sound of Music Live,1 win.,0,0,0,0,0,0,0,0,0,1
13727,After the Storm,2 nominations.,0,0,0,0,0,0,0,0,2,0
13879,The Passion,1 nomination.,0,0,0,0,0,0,0,0,0,0
13898,The Division: Agent Origins,1 nomination.,0,0,0,0,0,0,0,0,0,0
13997,Hold On,1 win.,0,0,0,0,0,0,0,0,0,1
14003,The Shining Star of Losers Everywhere,1 nomination.,0,0,0,0,0,0,0,0,0,0
14007,Solitaires. Le bal des sauvages,1 win.,0,0,0,0,0,0,0,0,0,1
14046,Mama,1 nomination.,0,0,0,0,0,0,0,0,0,0
14089,Flume Featuring Andrew Wyatt: Some Minds,2 nominations.,0,0,0,0,0,0,0,0,2,0
14136,Zusammen Allein,1 nomination.,0,0,0,0,0,0,0,0,0,0
14137,Strike a Pose,2 nominations.,0,0,0,0,0,0,0,0,2,0
14249,Houston; We Have a Problem,2 wins & 2 nominations.,0,0,0,0,0,0,0,0,2,2
14346,Close Encounters with Vilmos Zsigmond,2 nominations.,0,0,0,0,0,0,0,0,2,0
14432,The Return,2 wins & 2 nominations.,0,0,0,0,0,0,0,0,2,2
14599,Hearts of Spring,2 wins & 1 nomination.,0,0,0,0,0,0,0,0,0,2
14652,A Single Girl's Guide To...,1 nomination.,0,0,0,0,0,0,0,0,0,0
14761,Day 5,1 nomination.,0,0,0,0,0,0,0,0,0,0
14792,Business,1 nomination.,0,0,0,0,0,0,0,0,0,0
14800,Limbo,2 nominations.,0,0,0,0,0,0,0,0,2,0
14805,Ukraine on Fire,1 win.,0,0,0,0,0,0,0,0,0,1
14873,Cinema Dom Dinis,1 win.,0,0,0,0,0,0,0,0,0,1
14908,I Wanna Be with You,1 nomination.,0,0,0,0,0,0,0,0,0,0
15177,Fish Out of Water,1 nomination.,0,0,0,0,0,0,0,0,0,0
15180,Camp Unplug,2 nominations.,0,0,0,0,0,0,0,0,2,0
15219,The Baulkham Hills African Ladies Troupe,2 nominations.,0,0,0,0,0,0,0,0,2,0
15230,Me,1 nomination.,0,0,0,0,0,0,0,0,0,0
15234,Caged,1 win & 1 nomination.,0,0,0,0,0,0,0,0,0,1
15269,SoulMate,7 nominations.,0,0,0,0,0,0,0,0,7,0

In [113]:
df3.to_csv('Assignment3Q4.csv')